// Noms commerciaux -> molecules de la liste AMIS. v:1 = confirme dans une source officielle (ANSM/HAS/Vidal) ; v:0 = a verifier
const BRANDS_VERSION = "1.0 (10/2026)";
const BRANDS = [
{"b": "Acadione", "d": ["Tiopronine"], "v": 0},
{"b": "Adalate", "d": ["Nifédipine"], "v": 0},
{"b": "Agyrax", "d": ["Méclozine"], "v": 0},
{"b": "Alepsal", "d": ["Phénobarbital"], "v": 0},
{"b": "Alipza", "d": ["Pitavastatine"], "v": 0},
{"b": "Alloferine", "d": ["Alcuronium"], "v": 0},
{"b": "Atarax", "d": ["Hydroxyzine"], "v": 0},
{"b": "Avelox", "d": ["Moxifloxacine"], "v": 0},
{"b": "Avlocardyl", "d": ["Propranolol"], "v": 0},
{"b": "Azadose", "d": ["Azithromycine"], "v": 0},
{"b": "Azarga", "d": ["Timolol"], "v": 0},
{"b": "BCG", "d": ["Vaccins vivants"], "v": 0},
{"b": "Benadryl", "d": ["Diphénhydramine"], "v": 0},
{"b": "Bi-Tildiem", "d": ["Diltiazem"], "v": 0},
{"b": "Bitter Lemon", "d": ["Schweppes & Tonics"], "v": 0},
{"b": "Bramitob", "d": ["Tobramycine"], "v": 0},
{"b": "Buccolam", "d": ["Midazolam"], "v": 0},
{"b": "Bétoptic", "d": ["Bétaxolol"], "v": 0},
{"b": "Caduet", "d": ["Atorvastatine"], "v": 0},
{"b": "Cartéol", "d": ["Cartéolol"], "v": 0},
{"b": "Chronadalate", "d": ["Nifédipine"], "v": 0},
{"b": "Ciflox", "d": ["Ciprofloxacine"], "v": 0},
{"b": "Colimycine", "d": ["Colistine"], "v": 0},
{"b": "Coltramyl", "d": ["Thiocolchicoside"], "v": 0},
{"b": "Corgard", "d": ["Nadolol"], "v": 0},
{"b": "Cortancyl", "d": ["Corticoïdes"], "v": 0},
{"b": "Cosopt", "d": ["Timolol"], "v": 0},
{"b": "Crestor", "d": ["Rosuvastatine"], "v": 0},
{"b": "Célestène", "d": ["Corticoïdes"], "v": 0},
{"b": "Célocurine", "d": ["Suxaméthonium"], "v": 0},
{"b": "Dalacine", "d": ["Clindamycine"], "v": 0},
{"b": "Dantrium", "d": ["Dantrolène"], "v": 0},
{"b": "Debekacyl", "d": ["Dibékacin"], "v": 0},
{"b": "Dectancyl", "d": ["Corticoïdes"], "v": 0},
{"b": "Di-Hydan", "d": ["Phénytoïne"], "v": 0},
{"b": "Ditropan", "d": ["Oxybutynine"], "v": 0},
{"b": "Donormyl", "d": ["Doxylamine"], "v": 0},
{"b": "Driptane", "d": ["Oxybutynine"], "v": 0},
{"b": "Duotrav", "d": ["Timolol"], "v": 0},
{"b": "Décontractyl", "d": ["Méphénésine"], "v": 0},
{"b": "Elisor", "d": ["Pravastatine"], "v": 0},
{"b": "Entonox", "d": ["Monoxyde d'azote"], "v": 0},
{"b": "Esmeron", "d": ["Rocuronium"], "v": 0},
{"b": "Fervex", "d": ["Phéniramine"], "v": 0},
{"b": "Fever-Tree", "d": ["Schweppes & Tonics"], "v": 0},
{"b": "Fractal", "d": ["Fluvastatine"], "v": 0},
{"b": "Ganfort", "d": ["Timolol"], "v": 0},
{"b": "Gardénal", "d": ["Phénobarbital"], "v": 0},
{"b": "Gentalline", "d": ["Gentamicine"], "v": 0},
{"b": "Halfan", "d": ["Halofantrine"], "v": 0},
{"b": "Havlane", "d": ["Loprazolam"], "v": 1},
{"b": "Hexabrix", "d": ["Iode injectable"], "v": 0},
{"b": "Hydrocortisone Roussel", "d": ["Corticoïdes"], "v": 0},
{"b": "Hypnovel", "d": ["Midazolam"], "v": 0},
{"b": "Hémangiol", "d": ["Propranolol"], "v": 0},
{"b": "Imovane", "d": ["Zopiclone"], "v": 1},
{"b": "Indian Tonic", "d": ["Schweppes & Tonics"], "v": 0},
{"b": "Inegy", "d": ["Simvastatine"], "v": 0},
{"b": "Intron A", "d": ["Interférons alfa-2a/2b"], "v": 0},
{"b": "Iomeron", "d": ["Iode injectable"], "v": 0},
{"b": "Isoptine", "d": ["Vérapamil"], "v": 0},
{"b": "Isépalline", "d": ["Isépamicine"], "v": 0},
{"b": "Izilox", "d": ["Moxifloxacine"], "v": 0},
{"b": "Kalinox", "d": ["Monoxyde d'azote"], "v": 0},
{"b": "Kenacort", "d": ["Corticoïdes"], "v": 0},
{"b": "Ketek", "d": ["Telithromycine"], "v": 0},
{"b": "Kétalar", "d": ["Kétamine"], "v": 0},
{"b": "Largactil", "d": ["Chlorpromazine"], "v": 0},
{"b": "Lariam", "d": ["Méfloquine"], "v": 0},
{"b": "Lendormin", "d": ["Brotizolam"], "v": 0},
{"b": "Lescol", "d": ["Fluvastatine"], "v": 0},
{"b": "Lexomil", "d": ["Bromazépam"], "v": 1},
{"b": "Librax", "d": ["Chlordiazépoxide", "Clidinium"], "v": 0},
{"b": "Librium", "d": ["Chlordiazépoxide"], "v": 0},
{"b": "Likozam", "d": ["Clobazam"], "v": 1},
{"b": "Lincocine", "d": ["Lincomycine"], "v": 0},
{"b": "Liorésal", "d": ["Baclofène"], "v": 0},
{"b": "Lodalès", "d": ["Simvastatine"], "v": 0},
{"b": "Lopressor", "d": ["Métoprolol"], "v": 0},
{"b": "Lumirelax", "d": ["Méthocarbamol"], "v": 0},
{"b": "Lysanxia", "d": ["Prazépam"], "v": 1},
{"b": "M-M-RVaxPro", "d": ["Vaccins vivants"], "v": 0},
{"b": "Mag 2", "d": ["Magnésium per os", "Pidolate de Mg"], "v": 0},
{"b": "Magnevie B6", "d": ["Magnésium per os"], "v": 0},
{"b": "Magnevist", "d": ["Gadopentétate de méglumine"], "v": 0},
{"b": "Magnogène", "d": ["Magnésium per os"], "v": 0},
{"b": "Magné B6", "d": ["Magnésium per os"], "v": 0},
{"b": "Maxidrol", "d": ["Néomycine", "Polymyxine"], "v": 0},
{"b": "Meopa", "d": ["Monoxyde d'azote"], "v": 0},
{"b": "Miorel", "d": ["Thiocolchicoside"], "v": 0},
{"b": "Mivacron", "d": ["Mivacurium"], "v": 0},
{"b": "Moditen", "d": ["Fluphénazine"], "v": 0},
{"b": "Mogadon", "d": ["Nitrazépam"], "v": 1},
{"b": "Mono-Tildiem", "d": ["Diltiazem"], "v": 0},
{"b": "Multergan", "d": ["Thiazinamium"], "v": 0},
{"b": "Myolastan", "d": ["Tétrazépam"], "v": 0},
{"b": "Médrol", "d": ["Corticoïdes"], "v": 0},
{"b": "Nautamine", "d": ["Diphénhydramine"], "v": 0},
{"b": "Naxy", "d": ["Clarithromycine"], "v": 0},
{"b": "Nebcine", "d": ["Tobramycine"], "v": 0},
{"b": "Neurolithium", "d": ["Lithium"], "v": 0},
{"b": "Nicopatch", "d": ["Nicotine (patch)", "Patchs nicotiniques"], "v": 0},
{"b": "Nicorette", "d": ["Nicotine (patch)", "Patchs nicotiniques"], "v": 0},
{"b": "Nicotinell", "d": ["Nicotine (patch)", "Patchs nicotiniques"], "v": 0},
{"b": "Nimbex", "d": ["Cisatracurium"], "v": 0},
{"b": "Niquitin", "d": ["Nicotine (patch)", "Patchs nicotiniques"], "v": 0},
{"b": "Nivaquine", "d": ["Chloroquine"], "v": 0},
{"b": "Norcuron", "d": ["Vécuronium"], "v": 0},
{"b": "Nordaz", "d": ["Nordazépam"], "v": 0},
{"b": "Norflex", "d": ["Orphénadrine"], "v": 0},
{"b": "Normison", "d": ["Témazépam"], "v": 0},
{"b": "Nozinan", "d": ["Lévomépromazine"], "v": 0},
{"b": "Nuctalon", "d": ["Estazolam"], "v": 1},
{"b": "Nyogel", "d": ["Timolol"], "v": 0},
{"b": "Nétromicine", "d": ["Nétilmicine"], "v": 0},
{"b": "Oflocet", "d": ["Ofloxacine"], "v": 0},
{"b": "Okimus", "d": ["Quinine"], "v": 0},
{"b": "Olcadil", "d": ["Cloxazolam"], "v": 0},
{"b": "Omnipaque", "d": ["Iode injectable"], "v": 0},
{"b": "Optimine", "d": ["Azatadine dimaléate"], "v": 0},
{"b": "Optiray", "d": ["Iode injectable"], "v": 0},
{"b": "Pegasys", "d": ["Interférons alfa-2a/2b"], "v": 0},
{"b": "PegIntron", "d": ["Interférons alfa-2a/2b"], "v": 0},
{"b": "Pentothal", "d": ["Thiopental"], "v": 0},
{"b": "Persantine", "d": ["Dipyridamole", "Dipyridamole injectable"], "v": 0},
{"b": "Phénergan", "d": ["Prométhazine"], "v": 0},
{"b": "Plaquenil", "d": ["Hydroxychloroquine"], "v": 0},
{"b": "Polaramine", "d": ["Dexchlorphéniramine"], "v": 0},
{"b": "Polygynax", "d": ["Néomycine", "Polymyxine"], "v": 0},
{"b": "Primalan", "d": ["Méquitazine"], "v": 0},
{"b": "Priorix", "d": ["Vaccins vivants"], "v": 0},
{"b": "Péflacine", "d": ["Pefloxacine"], "v": 0},
{"b": "Quinidine Durbis", "d": ["Quinidine"], "v": 0},
{"b": "Quinimax", "d": ["Quinine"], "v": 0},
{"b": "Rapifen", "d": ["Alfentanil"], "v": 0},
{"b": "Rivotril", "d": ["Clonazépam"], "v": 0},
{"b": "Roferon", "d": ["Interférons alfa-2a/2b"], "v": 0},
{"b": "Rohypnol", "d": ["Flunitrazépam"], "v": 0},
{"b": "ROR Vax", "d": ["Vaccins vivants"], "v": 0},
{"b": "Rosuzet", "d": ["Rosuvastatine"], "v": 0},
{"b": "Rotarix", "d": ["Vaccins vivants"], "v": 0},
{"b": "RotaTeq", "d": ["Vaccins vivants"], "v": 0},
{"b": "Rythmol", "d": ["Propafénone"], "v": 0},
{"b": "Sanmigran", "d": ["Pizotifène"], "v": 0},
{"b": "Schweppes Indian Tonic", "d": ["Schweppes & Tonics"], "v": 0},
{"b": "Sectral", "d": ["Acébutolol"], "v": 0},
{"b": "Seloken", "d": ["Métoprolol"], "v": 0},
{"b": "Selozok", "d": ["Métoprolol"], "v": 0},
{"b": "Solu-Médrol", "d": ["Corticoïdes"], "v": 0},
{"b": "Solupred", "d": ["Corticoïdes"], "v": 0},
{"b": "Srilane", "d": ["Idrocilamide"], "v": 0},
{"b": "Stamaril", "d": ["Vaccins vivants"], "v": 0},
{"b": "Stilnox", "d": ["Zolpidem"], "v": 1},
{"b": "Stresam", "d": ["Etifoxine"], "v": 0},
{"b": "Séresta", "d": ["Oxazépam"], "v": 1},
{"b": "Sérécor", "d": ["Hydroquinidine"], "v": 0},
{"b": "Sévorane", "d": ["Sévoflurane"], "v": 0},
{"b": "Tahor", "d": ["Atorvastatine"], "v": 1},
{"b": "Tavanic", "d": ["Levofloxacine"], "v": 0},
{"b": "Tavegyl", "d": ["Clémastine fumarate"], "v": 0},
{"b": "Temesta", "d": ["Lorazépam"], "v": 1},
{"b": "Tenordate", "d": ["Aténolol"], "v": 0},
{"b": "Teoptic", "d": ["Cartéolol"], "v": 0},
{"b": "Théralène", "d": ["Alimémazine"], "v": 0},
{"b": "Tildiem", "d": ["Diltiazem"], "v": 0},
{"b": "Timoptol", "d": ["Timolol"], "v": 0},
{"b": "Tinset", "d": ["Oxatomide"], "v": 0},
{"b": "Tobi", "d": ["Tobramycine"], "v": 0},
{"b": "Tobrex", "d": ["Tobramycine"], "v": 0},
{"b": "Toplexil", "d": ["Oxomémazine"], "v": 0},
{"b": "Tracrium", "d": ["Atracurium"], "v": 0},
{"b": "Trancopal", "d": ["Chlormézanone"], "v": 0},
{"b": "Tranxène", "d": ["Clorazépate"], "v": 1},
{"b": "Trasicor", "d": ["Oxprénolol"], "v": 0},
{"b": "Trolovol", "d": ["D-pénicillinamine"], "v": 0},
{"b": "Tygacil", "d": ["Tigécycline"], "v": 0},
{"b": "Tégrétol", "d": ["Carbamazépine"], "v": 0},
{"b": "Télébrix", "d": ["Iode injectable"], "v": 0},
{"b": "Ténormine", "d": ["Aténolol"], "v": 0},
{"b": "Téralithe", "d": ["Lithium"], "v": 0},
{"b": "Ultravist", "d": ["Iode injectable"], "v": 0},
{"b": "Urbanyl", "d": ["Clobazam"], "v": 1},
{"b": "Valium", "d": ["Diazépam"], "v": 1},
{"b": "Varilrix", "d": ["Vaccins vivants"], "v": 0},
{"b": "Varivax", "d": ["Vaccins vivants"], "v": 0},
{"b": "Vasten", "d": ["Pravastatine"], "v": 0},
{"b": "Vesicare", "d": ["Solifenacine"], "v": 0},
{"b": "Victan", "d": ["Loflazépate d'éthyle"], "v": 1},
{"b": "Visipaque", "d": ["Iode injectable"], "v": 0},
{"b": "Visken", "d": ["Pindolol"], "v": 0},
{"b": "Vératran", "d": ["Clotiazépam"], "v": 1},
{"b": "Xalacom", "d": ["Timolol"], "v": 0},
{"b": "Xanax", "d": ["Alprazolam"], "v": 1},
{"b": "Xenetix", "d": ["Iode injectable"], "v": 0},
{"b": "Xylocard", "d": ["Lidocaïne IV"], "v": 0},
{"b": "Xylocaïne", "d": ["Lidocaïne IV"], "v": 0},
{"b": "Zeclar", "d": ["Clarithromycine"], "v": 0},
{"b": "Zithromax", "d": ["Azithromycine"], "v": 0},
{"b": "Zocor", "d": ["Simvastatine"], "v": 0},
{"b": "Zostavax", "d": ["Vaccins vivants"], "v": 0}
];
